ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

# Add your kibana plugins setup here
#RUN curl -L https://github.com/dlumbrer/kbn_network/releases/download/7.5.X-1/network_vis-7.tar.gz | tar xz -C /usr/share/kibana/plugins
